package eam.desarrollo.hospital.entidades;
import java.io.Serializable;
import java.sql.Time;
import java.util.Date;

/**
 * Model class of Citas.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Citas implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** IdCita. */
	private Integer Idcita;
	
	/** Fecha_cita. */
	private Date fechaCita;

	/** idProfesional. */
	private Integer idprofesional;

	/** Id_cliente. */
	private Integer idCliente;
	
	/** Hora_cita. */
	private String hora_cita;

	
	public Citas(Integer IdCita, Date fechaCita,String hora,Integer idprofesional, Integer idCliente) {
		super();
		this.Idcita = IdCita;
		this.fechaCita = fechaCita;
		this.hora_cita = hora;
		this.idprofesional = idprofesional;
		this.idCliente = idCliente;
	}
	

	public Integer getIdcita() {
		return Idcita;
	}



	public void setIdcita(Integer idcita) {
		Idcita = idcita;
	}



	public String getHora_cita() {
		return hora_cita;
	}



	public void setHora_cita(String hora_cita) {
		this.hora_cita = hora_cita;
	}



	public Date getFechaCita() {
		return fechaCita;
	}

	public void setFechaCita(Date fechaCita) {
		this.fechaCita = fechaCita;
	}

	public Integer getIdprofesional() {
		return idprofesional;
	}

	public void setIdprofesional(Integer idprofesional) {
		this.idprofesional = idprofesional;
	}

	public Integer getIdCliente() {
		return idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}
	
	

}
